package main.model;

public enum CycleParts {
	
	SPOKES,  RIM, TUBELESSTUBE, TUBE, TYRE, VALVE,
	SADDLE, SEATPOST,
	FRAME,
	CHAIN, CRANKARM, GEAR, PEDAL,
	BREAK, FORK, GEARCONTROL, HANDLEBARGRIP, HEADTUBE, SHOCKABSORBER
	
}
